# Generated by Django 3.2.10 on 2022-03-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
