# Generated by Django 3.2.10 on 2022-04-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_image',
        ),
    ]
