# Generated by Django 3.2.10 on 2022-04-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='select_sex',
            field=models.CharField(choices=[('M', 'Freshman'), ('W', 'Sophomore'), ('C', 'Junior')], default='M', max_length=5),
        ),
    ]
