# Generated by Django 3.2.10 on 2022-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_subcategory_select_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='select_sex',
            field=models.CharField(choices=[('M', 'MEN'), ('W', 'WOOMENS'), ('C', 'CHILD')], default='M', max_length=5),
        ),
    ]
