# Generated by Django 3.2.10 on 2022-04-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20220402_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='select_sex',
        ),
    ]
