# Generated by Django 3.2.10 on 2022-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_remove_subcategory_select_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('name',),
            },
        ),
    ]
