# Generated by Django 3.2.10 on 2022-04-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220402_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%<django.db.models.fields.related.ForeignKey>/%<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%<django.db.models.fields.related.ForeignKey>/%<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%<django.db.models.fields.related.ForeignKey>/%<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%<django.db.models.fields.related.ForeignKey>/%<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%<django.db.models.fields.related.ForeignKey>/%<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], default='40', max_length=200),
        ),
    ]
